### ISSUE TITLE
Client Crashes when joining server [1.12]

### ISSUE THREAD

**Issue by NoplixDE** [OreCruncher/DynamicSurroundings#132]
*Mod Version:*
Newest on 1.12
*Forge Version:*
Newest on 1.12

*Link to crash log (if applicable):*
https://gist.github.com/NoplixDE/3de29287a6feea47c81800314ab1847f

*Description:*
If I join my Server the "Client" Crashes, no the server.
If I change: 

# Enable Weapon/Tool Equip sound effect [default: true]
    B:"Equip Sound"=true

to

# Enable Weapon/Tool Equip sound effect [default: true]
    B:"Equip Sound"=false

It doesn't crash anymore.

**Comment by OreCruncher** [comment]
The fix for [#126] should fix it.  I should be pushing the JAR today/tomorrow.  Let me know if it does.

**Comment by OreCruncher** [comment]
Fix pushed to CurseForge.

**Comment by TheRActivator** [comment]
I still get an error when trying to join the server (Singleplayer Open to LAN with Hamachi
crash log:
	[13:49:03] [Netty Client IO #1/ERROR] [FML]: NetworkDispatcher exception
15:49:03	game	io.netty.handler.timeout.ReadTimeoutException: null
15:49:03	game	[13:49:03] [main/FATAL]: Error executing task
15:49:03	game	java.util.concurrent.ExecutionException: java.lang.NullPointerException
15:49:03	game	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_25]
15:49:03	game	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_25]
15:49:03	game	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
15:49:03	game	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1086) [bhz.class:?]
15:49:03	game	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bhz.class:?]
15:49:03	game	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
15:49:03	game	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
15:49:03	game	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
15:49:03	game	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
15:49:03	game	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
15:49:03	game	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
15:49:03	game	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
15:49:03	game	Caused by: java.lang.NullPointerException
15:49:03	game	at java.util.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1106) ~[?:1.8.0_25]
15:49:03	game	at java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1097) ~[?:1.8.0_25]
15:49:03	game	at net.minecraftforge.fml.common.eventhandler.EventBus.unregister(EventBus.java:162) ~[EventBus.class:?]
15:49:03	game	at org.blockartistry.DynSurround.client.handlers.EffectManager.unregister(EffectManager.java:90) ~[EffectManager.class:?]
15:49:03	game	at org.blockartistry.DynSurround.proxy.ProxyClient$2.run(ProxyClient.java:109) ~[ProxyClient$2.class:?]
15:49:03	game	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
15:49:03	game	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
15:49:03	game	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
15:49:03	game	... 9 more

**Comment by TheRActivator** [comment]
Not sure if it is the same error or a different error

**Comment by OreCruncher** [comment]
Different one.  Please open a new issue and post the complete client log.
